spring:
  ai:
    vectorstore:
      redis:
        initialize-schema: true
        index-name: ai-hospital
        prefix: ai-hospital-vectorstore
    dashscope:
      api-key: sk-5260f53be338461bb6a9a28545552dc4
      chat:
        options:
          model: qwen-plus
      embedding:
        options:
          model: text-embedding-v3
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/guiguxiaozhi?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

