spring:
  ai:
    dashscope:
      api-key: sk-5260f53be338461bb6a9a28545552dc4
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      chat:
        options:
          model: qwen-plus
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      connect-timeout: 3
      timeout: 2
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug

